# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand
from core.models.base.area_atendimento import AreaAtendimento


areasAtendimentos = ['GERAL', 'GINECOLOGIA E OBSTETRÍCIA', 'ACUPUNTURA', 'ALERGIA E IMUNOLOGIA', 'ANGIOLOGIA', 'CARDIOLOGIA', 'CIRURGIA CARDIOVASCULAR', 'CIRURGIA DA MÃO', 'CIRURGIA DE CABEÇA E PESCOÇO', 'CIRURGIA DO APARELHO DIGESTIVO', 'CIRURGIA GERAL', 'CIRURGIA ONCOLÓGICA', 'CIRURGIA PEDIÁTRICA', 'CIRURGIA PLÁSTICA', 'CIRURGIA TORÁCICA', 'CIRURGIA VASCULAR', 'CLÍNICA MÉDICA', 'COLOPROCTOLOGIA', 'DERMATOLOGIA', 'ENDOCRINOLOGIA E METABOLOGIA', 'ENDOSCOPIA', 'GASTROENTEROLOGIA', 'GENÉTICA MÉDICA', 'GERIATRIA', 'HEMATOLOGIA E HEMOTERAPIA', 'HOMEOPATIA', 'INFECTOLOGIA', 'MASTOLOGIA', 'MEDICINA DE EMERGÊNCIA', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 'MEDICINA DO TRABALHO', 'MEDICINA DE TRÁFEGO', 'MEDICINA ESPORTIVA', 'MEDICINA FÍSICA E REABILITAÇÃO', 'MEDICINA INTENSIVA', 'MEDICINA LEGAL E PERÍCIA MÉDICA', 'MEDICINA NUCLEAR', 'NEFROLOGIA', 'NEUROCIRURGIA', 'NEUROLOGIA', 'NUTROLOGIA', 'OFTALMOLOGIA', 'ONCOLOGIA CLÍNICA', 'ORTOPEDIA E TRAUMATOLOGIA', 'OTORRINOLARINGOLOGIA', 'PATOLOGIA', 'PATOLOGIA CLÍNICA/ MEDICINA LABORATORIAL', 'PEDIATRIA', 'PNEUMOLOGIA', 'PSIQUIATRIA', 'RADIOLOGIA', 'RADIOTERAPIA', 'REUMATOLOGIA', 'UROLOGIA']


class Command(BaseCommand):

    def add_arguments(self, parser):
        pass

    def handle(self, **options):
        print('INICIO')
        for area in areasAtendimentos:
            AreaAtendimento.objects.create(descricao=area)
        print('FIM')






