# Generated by Django 3.0.8 on 2020-12-10 09:57

import core.util.util_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaatendimento',
            name='teste',
            field=core.util.util_manager.UpperCaseCharField(max_length=255, null=True, verbose_name='Teste'),
        ),
    ]
