# Generated by Django 3.0.8 on 2021-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='descricao',
            field=models.CharField(default='Um médico comum', max_length=255, verbose_name='Descrição'),
        ),
    ]
