# Generated by Django 3.0.8 on 2020-12-10 00:26

import core.util.util_manager
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('retorno', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço')),
                ('tempo', models.TimeField(default=django.utils.timezone.now)),
                ('inicio_atendimento', models.TimeField(blank=True, null=True)),
                ('fim_atendimento', models.TimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('crm_soliciante', models.CharField(blank=True, max_length=7, verbose_name='CRM Médico Solicitante')),
            ],
            options={
                'verbose_name': 'ATENDIMENTO',
                'verbose_name_plural': 'ATENDIMENTOS',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Descrição')),
                ('desconto', models.IntegerField(verbose_name='Desconto')),
            ],
            options={
                'verbose_name': 'CONVENIO',
                'verbose_name_plural': 'CONVENIOS',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Nº')),
            ],
            options={
                'verbose_name': 'ENDEREÇO',
                'verbose_name_plural': 'ENDEREÇOS',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('dia', models.DateField()),
            ],
            options={
                'verbose_name': 'ESCALA',
                'verbose_name_plural': 'ESCALAS',
            },
        ),
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'verbose_name': 'LatLng',
                'verbose_name_plural': 'LatLngs',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('mae', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome da Mãe')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('data_nascimento', models.DateField(default=datetime.date.today)),
                ('cpf', models.CharField(blank=True, default='000.000.000-00', max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, default='0.000.000', max_length=9, verbose_name='RG')),
                ('idade', models.IntegerField(blank=True, default=10, verbose_name='Idade')),
                ('telefone', models.CharField(default='(87) 912345678', max_length=40, verbose_name='Telefone')),
                ('genero', models.IntegerField(default=1, verbose_name='Genero')),
                ('sobre', models.CharField(blank=True, default='', max_length=255, verbose_name='Sobre')),
                ('cliente_app', models.CharField(blank=True, default=None, max_length=255, verbose_name='Cliente App')),
            ],
            options={
                'verbose_name': 'PACIENTE',
                'verbose_name_plural': 'PACIENTES',
            },
        ),
        migrations.CreateModel(
            name='PacienteDepartamentoProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tipoatendimento',
            options={'verbose_name': 'TIPO DE ATENDIMENTO GERAL', 'verbose_name_plural': 'TIPOS DE ATENDIMENTOS GERAL'},
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='areaAtendimento',
        ),
        migrations.RemoveField(
            model_name='departamentoprofissional',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='departamentoprofissional',
            name='date_modificado',
        ),
        migrations.RemoveField(
            model_name='departamentoprofissional',
            name='tiposProfissionais',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='tipoprofissional',
            name='tiposAtendimentos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_app',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cliente App'),
        ),
        migrations.AddField(
            model_name='departamentoprofissional',
            name='tipo_profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoProfissional'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='codigo',
            field=core.util.util_manager.UpperCaseCharField(default='', max_length=10, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='areaAtendimento',
            field=models.ManyToManyField(to='core.AreaAtendimento', verbose_name='Area de Atendimento'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='tipo_profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoProfissional'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendentes', to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to='core.Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='documento',
            field=models.CharField(max_length=18, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='userProfissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.Empresa'),
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Atendimento')),
                ('departamento_profissional_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PacienteDepartamentoProfissional')),
            ],
            options={
                'verbose_name': 'PRONTUARIO',
                'verbose_name_plural': 'PRONTUARIOS',
            },
        ),
        migrations.AddField(
            model_name='pacientedepartamentoprofissional',
            name='departamentoProfissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DepartamentoProfissional'),
        ),
        migrations.AddField(
            model_name='pacientedepartamentoprofissional',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Departamento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Endereco'),
        ),
        migrations.CreateModel(
            name='EscalaIntervalo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('cor', models.CharField(max_length=20)),
                ('atendimento', models.IntegerField(blank=True, null=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Escala')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='departamentoProfissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DepartamentoProfissional'),
        ),
        migrations.CreateModel(
            name='AtendimentosDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('tipo_profissional', models.IntegerField()),
                ('tempo_padrao', models.TimeField(default=django.utils.timezone.now, verbose_name='Tempo Padrão')),
                ('valor_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço Padrão')),
                ('publico', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Departamento')),
                ('tipo_atendimento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoAtendimento')),
            ],
            options={
                'verbose_name': 'ATENDIMENTO DO DEPARTAMENTO',
                'verbose_name_plural': 'ATENDIMENTOS DO DEPARTAMENTO',
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='departamentoProfissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DepartamentoProfissional'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='intervalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escala_intervalo', to='core.EscalaIntervalo'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Paciente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tipoAtendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AtendimentosDepartamento'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Endereco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='convenios',
            field=models.ManyToManyField(to='core.Convenio'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='tiposAtendimentos',
            field=models.ManyToManyField(to='core.AtendimentosDepartamento', verbose_name='Tipos de Atendimento'),
        ),
    ]
