# Generated by Django 3.0.8 on 2021-04-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profissional_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
    ]
