# Generated by Django 3.0.8 on 2020-12-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_areaatendimento_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaatendimento',
            name='teste',
        ),
    ]
