# Generated by Django 3.0.4 on 2020-03-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeRazaoSocial', models.CharField(max_length=160, verbose_name='Nome/Razão Social')),
            ],
            options={
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
