# Generated by Django 3.0.5 on 2020-04-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=0, max_digits='100', max_length=100)),
                ('lng', models.DecimalField(decimal_places=0, max_digits='100', max_length=100)),
            ],
            options={
                'verbose_name': 'LatLng',
                'verbose_name_plural': 'LatLngs',
            },
        ),
    ]
