# Generated by Django 3.2 on 2021-05-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_paciente_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentosdepartamento',
            name='tipo_profissional',
        ),
    ]
