# Generated by Django 3.0.5 on 2020-04-10 01:16

import core.util.util_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200409_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='codigo',
            field=core.util.util_manager.UpperCaseCharField(default='', max_length=10, verbose_name='Código'),
        ),
    ]
