# Generated by Django 3.0.5 on 2020-04-10 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_profissional_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentoprofissional',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='departamentoprofissional',
            name='date_modificado',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='userProfissional', to=settings.AUTH_USER_MODEL),
        ),
    ]
