# Generated by Django 3.0.5 on 2020-04-13 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200410_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendentes', to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='areaAtendimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='core.AreaAtendimento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to='core.Empresa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.Empresa'),
        ),
    ]
