# Generated by Django 3.0.4 on 2020-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='documento',
            field=models.CharField(default=1, max_length=15, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_razao_social',
            field=models.CharField(max_length=255, verbose_name='Nome/Razão Social'),
        ),
    ]
