# Generated by Django 3.0.5 on 2020-04-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200413_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatendimento',
            name='areaAtendimento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='core.AreaAtendimento'),
            preserve_default=False,
        ),
    ]
