# Generated by Django 3.0.4 on 2020-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200405_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='documento',
            field=models.IntegerField(verbose_name='Documento'),
        ),
    ]
