# Generated by Django 3.0.5 on 2020-04-16 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tipoatendimento_areaatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprofissional',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Departamento'),
            preserve_default=False,
        ),
    ]
