# Generated by Django 3.0.5 on 2020-04-16 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tipoprofissional_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentoprofissional',
            name='tiposProfissionais',
        ),
        migrations.AddField(
            model_name='departamentoprofissional',
            name='tipo_profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoProfissional'),
            preserve_default=False,
        ),
    ]
