# Generated by Django 3.0.4 on 2020-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usuario',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default=2, max_length=100, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='senha',
            field=models.CharField(default=1, max_length=100, verbose_name='Senha'),
            preserve_default=False,
        ),
    ]
