# Generated by Django 3.0.5 on 2020-05-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200421_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='escalaIntervalo',
        ),
        migrations.RemoveField(
            model_name='tipoprofissional',
            name='tiposAtendimentos',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='retorno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tempo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='escalaintervalo',
            name='atendimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Atendimento'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='tiposAtendimentos',
            field=models.ManyToManyField(to='core.TipoAtendimento'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='tempo_padrao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departamentoprofissional',
            name='tipo_profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoProfissional'),
        ),
    ]
