# Generated by Django 3.0.4 on 2020-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200406_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='senha',
            field=models.CharField(default=1, max_length=255, verbose_name='Senha'),
            preserve_default=False,
        ),
    ]
