# Generated by Django 3.0.4 on 2020-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
