# Generated by Django 3.0.5 on 2020-05-05 20:32

import core.util.util_manager
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200505_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tempo',
            field=models.TimeField(default=datetime.datetime(2020, 5, 5, 20, 32, 47, 905265)),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='tiposAtendimentos',
            field=models.ManyToManyField(to='core.TipoAtendimento', verbose_name='Tipos de Atendimento'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='areaAtendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AreaAtendimento', verbose_name='Area de Atendimento'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='descricao',
            field=core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='tempo_padrao',
            field=models.TimeField(default=datetime.datetime(2020, 5, 5, 20, 32, 47, 899284), verbose_name='Tempo Padrão'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='valor_padrao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço Padrão'),
        ),
    ]
