# Generated by Django 3.0.4 on 2020-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200406_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usuario',
            field=models.CharField(max_length=255, unique=True, verbose_name='Usuario'),
        ),
    ]
