# Generated by Django 3.0.5 on 2020-05-22 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200522_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='fim_atendimento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='inicio_atendimento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tempo',
            field=models.TimeField(default=datetime.datetime(2020, 5, 22, 1, 51, 58, 992263)),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='tempo_padrao',
            field=models.TimeField(default=datetime.datetime(2020, 5, 22, 1, 51, 58, 985281), verbose_name='Tempo Padrão'),
        ),
    ]
