# Generated by Django 3.0.4 on 2020-04-06 15:45

import core.util.util_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200406_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'EMPRESA', 'verbose_name_plural': 'EMPRESAS'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'USUARIO', 'verbose_name_plural': 'USUARIOS'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_razao_social',
            field=core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Nome/Razão Social'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nome',
            field=core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='senha',
            field=core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usuario',
            field=core.util.util_manager.UpperCaseCharField(max_length=255, unique=True, verbose_name='Usuario'),
        ),
    ]
