# Generated by Django 3.0.5 on 2020-06-02 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200522_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='tempo',
            field=models.TimeField(default=datetime.datetime(2020, 6, 2, 17, 32, 21, 572251)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='documento',
            field=models.CharField(max_length=18, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='tempo_padrao',
            field=models.TimeField(default=datetime.datetime(2020, 6, 2, 17, 32, 21, 566267), verbose_name='Tempo Padrão'),
        ),
    ]
