# Generated by Django 3.0.4 on 2020-04-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200406_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
