# Generated by Django 3.0.5 on 2020-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='documento',
        ),
    ]
