# Generated by Django 3.0.5 on 2020-04-08 17:54

import core.util.util_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_empresa_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Nome')),
                ('descricao', core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'DEPARTAMENTO',
                'verbose_name_plural': 'DEPARTAMENTOS',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='documento',
            field=models.IntegerField(unique=True, verbose_name='Documento'),
        ),
    ]
