# Generated by Django 3.0.5 on 2020-06-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200606_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatendimento',
            name='tipo_prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoProfissional'),
        ),
    ]
