# Generated by Django 3.0.5 on 2020-06-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tipoatendimento_tipo_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoatendimento',
            old_name='tipo_prof',
            new_name='tipo_profissional',
        ),
    ]
