# Generated by Django 3.0.5 on 2020-07-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200606_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('cliente_app', models.CharField(blank=True, default=None, max_length=255, verbose_name='Cliente App')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='departamento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_app',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cliente App'),
        ),
        migrations.CreateModel(
            name='PacienteDepartamentoProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('departamentoProfissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DepartamentoProfissional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
