# Generated by Django 3.0.5 on 2020-04-09 16:02

import core.util.util_manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0023_departamento_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Nome')),
                ('usuario', core.util.util_manager.UpperCaseCharField(max_length=255, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('senha', core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Senha')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendentes', to='core.Empresa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendentes', to='auth.Group', verbose_name='Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='userAtendente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'USUARIO',
                'verbose_name_plural': 'USUARIOS',
            },
        ),
    ]
