# Generated by Django 3.0.5 on 2020-07-08 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200708_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Paciente'),
        ),
    ]
