# Generated by Django 3.0.5 on 2020-07-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200708_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
