# Generated by Django 3.0.5 on 2020-07-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_atendimento_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='dia',
        ),
    ]
