# Generated by Django 3.0.5 on 2020-04-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200409_1952'),
        ('core', '0026_auto_20200409_1946'),
    ]

    operations = [
    ]
