# Generated by Django 3.0.5 on 2020-04-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20200409_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='departamento',
        ),
    ]
