# Generated by Django 3.0.5 on 2020-07-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_atendimento_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(default=10, verbose_name='Idade'),
        ),
    ]
