# Generated by Django 3.0.5 on 2020-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_paciente_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(default='(87) 912345678', max_length=40, verbose_name='Telefone'),
        ),
    ]
