# Generated by Django 3.0.5 on 2020-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_paciente_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.IntegerField(default=1, verbose_name='Genero'),
        ),
    ]
