# Generated by Django 3.0.5 on 2020-07-14 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_paciente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('observacao', models.CharField(max_length=255, verbose_name='Observação')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('departamento_profissional_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PacienteDepartamentoProfissional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
