# Generated by Django 3.0.5 on 2020-07-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_prontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='peso',
            field=models.FloatField(),
        ),
    ]
