# Generated by Django 3.0.5 on 2020-07-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200714_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
