# Generated by Django 3.0.5 on 2020-07-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200714_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'verbose_name': 'PRONTUARIO', 'verbose_name_plural': 'PRONTUARIOS'},
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits='8', max_length=8),
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lng',
            field=models.DecimalField(decimal_places=2, max_digits='8', max_length=8),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
