# Generated by Django 3.0.5 on 2020-07-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200714_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlng',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits='8'),
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lng',
            field=models.DecimalField(decimal_places=2, max_digits='8'),
        ),
    ]
