# Generated by Django 3.0.5 on 2020-07-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200714_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlng',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lng',
            field=models.FloatField(),
        ),
    ]
