# Generated by Django 3.0.8 on 2020-07-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200714_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
