# Generated by Django 3.0.8 on 2020-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_atendimento_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='intervalo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
