# Generated by Django 3.0.8 on 2020-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200729_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='dia',
            field=models.DateField(),
        ),
    ]
