# Generated by Django 3.0.8 on 2020-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200729_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
