# Generated by Django 3.0.8 on 2020-07-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_atendimento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='data',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='intervalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escala_intervalo', to='core.EscalaIntervalo'),
        ),
        migrations.AlterField(
            model_name='escalaintervalo',
            name='atendimento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
