# Generated by Django 3.0.8 on 2020-08-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200729_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='areaAtendimento',
        ),
        migrations.RemoveField(
            model_name='tipoprofissional',
            name='departamento',
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Departamento'),
        ),
    ]
