# Generated by Django 3.0.8 on 2020-08-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200806_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoatendimento',
            name='descricao',
        ),
    ]
