# Generated by Django 3.0.8 on 2020-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_tipoatendimento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatendimento',
            name='descricao',
            field=models.CharField(default='Padrão', max_length=255, verbose_name='Descricao'),
        ),
    ]
