# Generated by Django 3.0.8 on 2020-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_tipoatendimento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descricao'),
        ),
    ]
