# Generated by Django 3.0.8 on 2020-08-24 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200806_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoatendimento',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='tipoatendimento',
            name='publico',
        ),
        migrations.RemoveField(
            model_name='tipoatendimento',
            name='tempo_padrao',
        ),
        migrations.RemoveField(
            model_name='tipoatendimento',
            name='valor_padrao',
        ),
        migrations.CreateModel(
            name='AtendimentosDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('tipo_profissional', models.IntegerField(max_length=4)),
                ('tempo_padrao', models.TimeField(default=django.utils.timezone.now, verbose_name='Tempo Padrão')),
                ('valor_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço Padrão')),
                ('publico', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Departamento')),
                ('tipo_atendimento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoAtendimento')),
            ],
            options={
                'verbose_name': 'TIPO DE ATENDIMENTO',
                'verbose_name_plural': 'TIPOS DE ATENDIMENTOS',
            },
        ),
    ]
