# Generated by Django 3.0.8 on 2020-08-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200824_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimentosdepartamento',
            options={'verbose_name': 'ATENDIMENTO DO DEPARTAMENTO', 'verbose_name_plural': 'ATENDIMENTOS DO DEPARTAMENTO'},
        ),
        migrations.AlterField(
            model_name='profissional',
            name='tiposAtendimentos',
            field=models.ManyToManyField(to='core.AtendimentosDepartamento', verbose_name='Tipos de Atendimento'),
        ),
    ]
