# Generated by Django 3.0.8 on 2020-08-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20200824_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoatendimento',
            options={'verbose_name': 'TIPO DE ATENDIMENTO GERAL', 'verbose_name_plural': 'TIPOS DE ATENDIMENTOS GERAL'},
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipoAtendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AtendimentosDepartamento'),
        ),
    ]
