# Generated by Django 3.0.8 on 2020-08-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20200825_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentosdepartamento',
            name='nome',
            field=models.CharField(blank=True, default='CANAL', max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
