# Generated by Django 3.0.8 on 2020-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_atendimentosdepartamento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='peso',
        ),
        migrations.AlterField(
            model_name='atendimentosdepartamento',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
