# Generated by Django 3.0.8 on 2020-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200827_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='mae',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
    ]
