# Generated by Django 3.0.8 on 2020-10-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200827_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='departamento_profissional_paciente',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='atendimento',
            field=models.OneToOneField(default=191, on_delete=django.db.models.deletion.PROTECT, to='core.Atendimento'),
        ),
    ]
