# Generated by Django 3.0.8 on 2020-10-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20201030_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='departamento_profissional_paciente',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='core.PacienteDepartamentoProfissional'),
        ),
    ]
