# Generated by Django 3.0.8 on 2020-10-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_prontuario_departamento_profissional_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='departamento_profissional_paciente',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='core.PacienteDepartamentoProfissional'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
