# Generated by Django 3.0.8 on 2020-10-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20201030_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='atendimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Atendimento'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='departamento_profissional_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PacienteDepartamentoProfissional'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observação'),
        ),
    ]
