# Generated by Django 3.0.8 on 2020-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20201030_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoatendimento',
            name='areaAtendimento',
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='areaAtendimento',
            field=models.ManyToManyField(to='core.AreaAtendimento', verbose_name='Area de Atendimento'),
        ),
    ]
