# Generated by Django 3.0.8 on 2020-12-04 16:47

import core.util.util_manager
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20201204_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Rua')),
                ('bairro', core.util.util_manager.UpperCaseCharField(max_length=100, verbose_name='Bairro')),
                ('cidade', core.util.util_manager.UpperCaseCharField(max_length=100, verbose_name='Cidade')),
                ('estado', core.util.util_manager.UpperCaseCharField(max_length=2, verbose_name='Estado')),
                ('numero', core.util.util_manager.UpperCaseCharField(max_length=50, verbose_name='Nº')),
            ],
            options={
                'verbose_name': 'ENDEREÇO',
                'verbose_name_plural': 'ENDEREÇOS',
            },
        ),

    ]
