# Generated by Django 3.0.8 on 2020-12-04 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20201204_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, default='000.000.000-00', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, default='0.000.000', max_length=9, verbose_name='RG'),
        ),
    ]
