# Generated by Django 3.0.8 on 2020-12-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_departamento_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='end',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
    ]
