# Generated by Django 3.0.8 on 2020-12-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20201204_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='end',
            new_name='endereco',
        ),
    ]
