# Generated by Django 3.0.8 on 2020-12-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20201204_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(blank=True, default=10, verbose_name='Idade'),
        ),
    ]
