# Generated by Django 3.0.8 on 2020-12-09 12:52

import core.util.util_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20201209_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', core.util.util_manager.UpperCaseCharField(max_length=255, verbose_name='Descrição')),
                ('desconto', models.IntegerField(verbose_name='Desconto')),
            ],
            options={
                'verbose_name': 'CONVENIO',
                'verbose_name_plural': 'CONVENIOS',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='convenios',
            field=models.ManyToManyField(to='core.Convenio'),
        ),
    ]
