# Generated by Django 3.0.8 on 2020-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20201209_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='crm_soliciante',
            field=models.CharField(blank=True, max_length=7, verbose_name='CRM Médico Solicitante'),
        ),
    ]
