# Generated by Django 3.0.8 on 2021-04-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Lista de LandingPage',
                'verbose_name_plural': 'Lista de LandingPage',
            },
        ),
    ]
