# Generated by Django 3.0.8 on 2021-04-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprofissional',
            name='agenda',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listaprofissional',
            name='especialidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listaprofissional',
            name='local_atendimento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listaprofissional',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
