# Generated by Django 3.0.8 on 2021-04-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210419_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprofissional',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
