# Generated by Django 3.0.8 on 2021-04-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_listaprofissional_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprofissional',
            name='imagem',
            field=models.ImageField(default='', upload_to='media/images/profs'),
        ),
    ]
