# Generated by Django 3.0.8 on 2021-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20210419_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprofissional',
            name='imagem',
            field=models.ImageField(default='', upload_to='images/profs'),
        ),
    ]
