# Generated by Django 3.0.8 on 2021-04-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20210419_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Lista de Empresa LandingPage',
                'verbose_name_plural': 'Lista de Empresa LandingPage',
            },
        ),
    ]
