# Generated by Django 3.0.8 on 2021-04-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_listaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprofissional',
            name='listaempresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prof', to='cliente.ListaEmpresa'),
        ),
    ]
