# Generated by Django 3.2 on 2021-04-21 16:04

import cliente.modulos.landingpage.ListaProfissional
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_listaprofissional_listaempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprofissional',
            name='imagem',
            field=models.ImageField(default='', storage=cliente.modulos.landingpage.ListaProfissional.OverwriteStorage(), upload_to='images/profs'),
        ),
    ]
