# Generated by Django 3.2 on 2021-04-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_paciente_idade'),
        ('cliente', '0008_alter_listaprofissional_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprofissional',
            name='especi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='espec', to='core.tipoprofissional'),
        ),
    ]
