# Generated by Django 3.2 on 2021-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_remove_listaprofissional_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaempresa',
            name='nome_slug',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
