# Generated by Django 3.2 on 2021-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_paciente_idade'),
        ('cliente', '0011_listaempresa_nome_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprofissional',
            name='especi',
        ),
        migrations.AddField(
            model_name='listaprofissional',
            name='especi',
            field=models.ManyToManyField(default=1, related_name='espec', to='core.TipoProfissional'),
        ),
    ]
