# Generated by Django 3.2 on 2021-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_alter_listaprofissional_especi'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprofissional',
            name='servicos',
            field=models.TextField(default=''),
        ),
    ]
