# Generated by Django 3.2.3 on 2021-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_auto_20210521_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'País',
            },
        ),
    ]
