# Generated by Django 3.2.3 on 2021-05-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'PAÍS', 'verbose_name_plural': 'PAÍSES'},
        ),
        migrations.AddField(
            model_name='listaempresa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listaempresa',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.pais'),
        ),
        migrations.AddField(
            model_name='listaprofissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
