# Generated by Django 3.2.3 on 2021-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_auto_20210524_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprofissional',
            name='telefone1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listaprofissional',
            name='telefone2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
