# Generated by Django 3.2.3 on 2021-06-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0019_auto_20210619_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprofissional',
            name='telefone2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
