# Generated by Django 3.2.3 on 2021-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_alter_listaprofissional_telefone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=4)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
