# Generated by Django 3.2.3 on 2021-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaempresa',
            name='cidade',
            field=models.ManyToManyField(to='cliente.Cidade'),
        ),
    ]
