# Generated by Django 3.2.3 on 2021-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0024_rename_cidade_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endereco',
            name='rua',
            field=models.CharField(default='', max_length=100),
        ),
    ]
