# Generated by Django 3.2.3 on 2021-06-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_auto_20210621_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaempresa',
            name='cidade',
        ),
        migrations.AddField(
            model_name='listaempresa',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to='cliente.endereco'),
        ),
    ]
