from .base import *
from core.modulos.empresa.empresa import Empresa
from core.modulos.user_profile.user_profile import UserProfile
from core.modulos.departamento.departamento import Departamento
from core.modulos.atendente.atendente import Atendente
from core.modulos.cliente.cliente import Cliente
from core.modulos.tipo_atendimento.tipo_atendimento import TipoAtendimento
from core.modulos.tipo_profissional.tipo_profissional import TipoProfissional
from core.modulos.profissional.profissional import Profissional
from core.modulos.profissional.profissional import DepartamentoProfissional
from core.modulos.escala.escala import Escala
from core.modulos.escala.escala import EscalaIntervalo
from core.modulos.atendimento.atendimento import Atendimento
