from .base import *
from core.modulos.empresa.empresa import Empresa
from core.modulos.user_profile.user_profile import UserProfile
from core.modulos.departamento.departamento import Departamento
from core.modulos.atendente.atendente import Atendente
from core.modulos.tipo_atendimento.tipo_atendimento import TipoAtendimento
from core.modulos.tipo_profissional.tipo_profissional import TipoProfissional
from core.modulos.profissional.profissional import Profissional
from core.modulos.profissional.profissional import DepartamentoProfissional
