class LabesProperty(object):
    # LABELS
    USUARIO = 'USUARIO'
    USUARIOS = 'USUARIOS'
    PERFIL = 'PERFIL'
    NOME = 'NOME'
    EMAIL = 'EMAIL'
    DOCUMENTO = 'DOCUMENTO'
    SALVAR = 'SALVAR'
    CANCELAR = 'CANCELAR'
    DEPARTAMENTO = "DEPARTAMENTO"
    DEPARTAMENTOS = "DEPARTAMENTOS"
    ATENDENTE = "ATENDENTE"
    ATENDENTES = "ATENDENTES"
    EMPRESA = "EMPRESA"
    EMPRESAS = "EMPRESAS"
    NOVA = "NOVA"
    NOVO = "NOVO"


    EDITAR = "EDITAR"
    BUSCAR = 'BUSCAR'
    ACOES = 'AÇÕES'
    CAMPO_BUSCA = 'CAMPO DE BUSCA'

    # MENSAGENS
    MSG_SALVO_SUCESSO = 'SALVO COM SUCESSO'
    MSG_EDITADO_SUCESSO = 'EDITADO COM SUCESSO'

    # MENSAGENS ERROS
    ERROR_NOME_USUARIO_EXISTE = NOME + ' DE USUÁRIO JÁ EXISTE'
    ERROR_EMAIL_USUARIO_EXISTE = EMAIL + ' DE USUÁRIO JÁ EXISTE'
